import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quote Rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Quote Rating</h1>

        <p className={styles.description}>
          Hier bewerten wir was gesprochen<sup>*</sup> wurde.
        </p>
        <p className="footNote">*Oder anderweitig kommuniziert</p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Bewerten &rarr;</h2>
            <p>So tindermäßig halt.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Auswertung &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
