import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import serverPic from "../public/serverPic.webp";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Quote Rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.titleContainer}>
          <div className={styles.title}>
            <div className={styles.titleImg}>
              <Image src={serverPic} alt="server icon" />
            </div>

            <div className={styles.titleText}>
              <p className={styles.titleUser}>
                ??? <span className={styles.titleDate}>Yesterday at 10:38</span>
              </p>
              <p className={styles.titleQuote}>
                <div className={styles.titleBlockQuoteThingy} />{" "}
                <span className={styles.titleQuoteText}>
                  Hier werden Zitate bewertet
                </span>
              </p>
              <p>— Joa</p>
            </div>
            {/*<h1 className={styles.title}>Quote Rating</h1>
          <p className={styles.description}>
            Hier bewerten wir was gesprochen<sup>*</sup> wurde.
          </p>
          <p className="footNote">*Oder anderweitig kommuniziert</p> */}
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="/rate">
            <a className={styles.card}>
              <h2>Bewerten &rarr;</h2>
              <p>So tindermäßig halt.</p>
            </a>
          </Link>

          <Link href="/stats">
            <a className={styles.card}>
              <h2>Auswertung &rarr;</h2>
              <p>Eher so excelmäßig</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
