import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Quote from "../components/quote";
import styles from "../styles/Rate.module.css";

type Props = {
  quote: QuoteData;
};

type QuoteData = {
  avatar_url?: string;
  id: number;
  content: string;
  author_id: number;
  sent_at: number;
  score: number;
};

const fetcher = (input: RequestInfo | URL, init?: RequestInit) =>
  fetch(input, init).then((res) => res.json());

const Rate = (props: Props) => {
  const [quote, setQuote] = useState(props.quote);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quote Rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Quote quote={quote} />
        <div>
          <button
            onClick={async () => {
              setQuote(
                await (await fetch("http://127.0.0.1:8000/quote")).json()
              );
            }}
          >
            New quote
          </button>
        </div>
      </main>
    </div>
  );
};

export async function getServerSideProps(
  context: any
): Promise<{ props: Props }> {
  return {
    props: {
      quote: await (await fetch("http://127.0.0.1:8000/quote")).json(),
    }, // will be passed to the page component as props
  };
}
export default Rate;
