import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Rate.module.css";
import useSWR from "swr";

const fetcher = (input: RequestInfo | URL, init?: RequestInit) =>
  fetch(input, init).then((res) => res.json());

const Rate: NextPage = () => {
  const { data, error } = useSWR("http://localhost:8000/quote", fetcher);
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Quote Rating</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
    </div>
  );
};

export default Rate;
